pylast/pylast

tests/test_pylast.py

If the test environment variables aren't set, this will skip the tests when run with py.test, for example on Travis CI.
If run as a standard Python script, it raises `Skipped: Missing environment variables: PYLAST_USERNAME etc.`, and ends the test, in a similar way to the previous `KeyError`.
Short-term fix for #115. A longer-term fix is to implement #105.

Skip if PYLAST_USERNAME etc. env vars missing

---

.travis.yml
README.md
RELEASING.md
pylast/__init__.py
setup.py
tests/test_pylast.py
tox.ini

Build things:
* Integration tests currently run against the real Last.fm network and occasionally fail due to network errors. Ideally this could be mocked to run offline (see https://github.com/pylast/pylast/issues/105) but for now, use flaky to rerun failing integration tests. This may need fine-tuning.
* pep8 (version 1.6.2) is now more strict and fails the lint test due to things like spaces around operators.  (Version 1.5.7 didn't fail.) Fix these. 
* Run lint tests first. They only take about 30 seconds compared to 8-10 minutes for the full tests.
* Remove an unused import.
Also:
* Add a release checklist.

Build improvements

---

pylast/__init__.py
tests/test_pylast.py

Last.fm began serving a deprecation notice for artist.getImages in 2013 after having delisted it for over a year.
www.last.fm/group/Last.fm+Web+Services/forum/21604/_/2216689
http://wayback.archive.org/web/20120114035312/http://www.last.fm/api/show/artist.getImages
Calling the API now results in:
```xml
<lfm status="failed">
<error code="27">The artist.getImages method has been deprecated.</error>
</lfm>
```
pylast has been returning a deprecation exception since https://github.com/pylast/pylast/commit/d3dba1475ab1615aae421d1e418f9134554c561c#diff-fcdfb9e45a4cd992ea6f74b1eea6123cR2024 (Mar 7, 2014), released in pylast 1.0.0 (Jul 29, 2014):
```python
def get_images(self, order=IMAGES_ORDER_POPULARITY, limit=None):
"""
The artist.getImages method has been deprecated by Last.fm.
"""
raise …
```

Remove artist.getImages and deprecation note

---

pylast/__init__.py
tests/test_pylast.py

Added support for [artist.getCorrection](http://www.lastfm.com.br/api/show/artist.getCorrection) and [track.getCorrection](http://www.lastfm.com.br/api/show/track.getCorrection).
Don't know, maybe I overlooked the Track.get_correction() . The request has two 'name' elements, I'm picking the first one, right? 
And what about try to correct by default?

Support for artist.getCorrection and track.getCorrection

---

pylast/__init__.py

Fixes https://github.com/pylast/pylast/issues/141 without breaking Libre.fm support.
Replaces PR #144.
---
`_collect_nodes()` contains the line:
```python
main = doc.documentElement.childNodes[1]
```
However, `doc.documentElement.childNodes` looks like this:
```
[<DOM Element: recenttracks at 0x10ba9e9e0>, <DOM Text node "u'\n'">]
```
Whatever used to be in index [1] is clearly not what we want now. Changing that `[1]` to `[0]` fixes it.
---
Without the fix:
> 71 failed, 85 passed 
https://travis-ci.org/pylast/pylast/builds/78444843
With the fix:
>  63 failed, 93 passed
https://travis-ci.org/hugovk/pylast/jobs/78570768

Fix get_recent_tracks (and more)

---

pylast/__init__.py
tests/test_pylast.py

When calling `.get_mbid()` on a track that has no listed MBID, return None instead of the artist's MBID.
```
<lfm status="ok">
<track>
<name>Set It Off</name>
<url>http://www.last.fm/music/Static-X/_/Set+It+Off</url>
<duration>0</duration>
<streamable fulltrack="0">0</streamable>
<listeners>39822</listeners>
<playcount>210863</playcount>
<artist>
<name>Static-X</name>
<mbid>8ac9e35c-e92d-4030-99ef-ba4127b1555c</mbid>
<url>http://www.last.fm/music/Static-X</url>
</artist>
...
```
Fixes #146.
Includes test, `test_track_with_no_mbid`.
Note: build is failing due to [Last.fm Re-imagined](https://getsatisfaction.com/lastfm/topics/api-known-issues), but:
* With just the test: 64 failed, 93 passed
https://travis-ci.org/hugovk/pylast/jobs/79183300
* With the fix:  63 failed, 94 passed, including …

Only get the top-level <mbid>

---

pylast/__init__.py

Temporary fix for minidom.parsestring error related to opensearch namespace.
Same as https://github.com/pylast/pylast/pull/153 but into pylast:temp-fix-minidom branch.

replaced opensearch: as empty str

---

pylast/__init__.py

Fixes album.get_tracks()
lastfm = pylast.LastFMNetwork(API_KEY, API_SECRET,
username = username, password_hash = password_hash)
mono_album = lastfm.get_album("MONO", "Hymn To The Immortal Wind")
print mono_album.get_tracks()
---
Before fix:
Traceback (most recent call last):
File "C:/Users/user/Projects/pylast/test_pylast.py", line 12, in <module>
print mono_album.get_tracks()
File "C:\Users\user\Projects\pylast\pylast\__init__.py", line 1862, in get_tracks
return XSPF(uri, self.network).get_tracks()
File "C:\Users\user\Projects\pylast\pylast\__init__.py", line 3185, in get_tracks
doc = self._request('playlist.fetch', True)
File "C:\Users\user\Projects\pylast\pylast\__init__.py", line 1308, in _request
return _Request(self.network, method_name, params).execute(cacheable)
File …

Fix album.get_tracks()

---

pylast/__init__.py

`.next()` is renamed `.__next__` in py3k, use `next()`

x.next() -> next(x) for python3 compat

---

.gitignore
tests/test_pylast.py

Specifically skip those that cause the exception `pylast.WSError` "Invalid Method - No method with that name in this package".
Last.fm broke these some time around 17th August 2015 when they relaunched ("re-imagined") their website.

Skip tests caused by the broken Last.fm API

---

tox.ini

Travis started [failing during installation](https://travis-ci.org/pylast/pylast/jobs/107969481) (which was [working before](https://travis-ci.org/pylast/pylast/jobs/98505653)) with:
```
lint installdeps: coverage, pep8, pyyaml, pyflakes, clonedigger
ERROR: invocation failed (exit code 2), logfile: /home/travis/build/pylast/pylast/.tox/lint/log/lint-1.log
ERROR: actionid: lint
msg: getenv
cmdargs: [local('/home/travis/build/pylast/pylast/.tox/lint/bin/pip'), 'install', '--download-cache=/home/travis/.pipcache', 'coverage', 'pep8', 'pyyaml', 'pyflakes', 'clonedigger']
env: {'PYLAST_API_SECRET': '', 'rvm_version': '1.26.8 (1.26.8)', 'LC_CTYPE': 'en_US.UTF-8', 'RUBY_VERSION': 'ruby-1.9.3-p551', 'MERB_ENV': 'test', 'NVM_DIR': '/home/travis/.nvm', 'TRAVIS_REPO_SLUG': 'pylast/pylast', 'HOME': …
```

Fix build: no such option: --download-cache

---

tests/test_pylast.py

Last.fm broke these some time around 17th August 2015 when they relaunched ("re-imagined") their website.
Some of these are still documented in the trimmed [Last.fm API docs](http://www.last.fm/api), but the live XML examples are missing certain attributes or return the wrong thing or are just broken.
See also https://github.com/pylast/pylast/pull/164.
--
[Current test status (Python 2.7/Travis CI):](https://travis-ci.org/hugovk/pylast/jobs/125216202) 
`=================== 99 passed, 59 skipped in 229.55 seconds ====================`

Skip broken tests caused by the broken Last.fm API

---

.gitignore
pylast/__init__.py
setup.py

Only use HTTPS

---

.travis.yml
README.md
pylast/__init__.py
setup.py

CPython 3.3 is no longer supported after September 29, 2017.
https://en.wikipedia.org/wiki/CPython#Version_history
https://www.python.org/dev/peps/pep-0398/

Drop support for Python 3.3

---

pylast/__init__.py
tests/test_pylast.py
tox.ini

Cherry-picked from #200, after enabling output of warnings on Travis CI.
Before the fix, 297 `ResourceWarning`s on Python 3.6:
```
tests/test_pylast.py::TestPyLast::test_add_album
/home/travis/build/pylast/pylast/pylast/__init__.py:1059: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.7', 33318), raddr=('64.30.224.206', 443)>
response = self._download_response()
```
https://travis-ci.org/pylast/pylast/jobs/276818610#L791
After, just one:
```
tests/test_pylast.py::TestPyLast::test_init_with_token
/home/travis/build/pylast/pylast/tests/test_pylast.py:2172: ResourceWarning: unclosed <ssl.SSLSocket fd=44, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.11', 47804), …
```

Fix unclosed SSLSocket warning

---

.travis.yml

Reverts #158, because Tox has been fixed:
https://github.com/tox-dev/tox/issues/285

Use latest Tox

---

pylast/__init__.py
tests/test_pylast.py

* Continuation of #211, #218 and #222: the only place`submission_server` was used was removed in #218.
* Remove `_get_name_from_code`, it was never finished and can be implemented outside the scope of pylast.
* The six removed attributes aren't used anywhere and date from at least pylast 0.5.
* `_pad_list` is unused, internal, and not so useful.
* `extract_items` is unused. I added tests but it wasn't working, so let's just remove it as I don't think it's so useful.
* Test a few previously untested things.

Remove redundant code

---

pylast/__init__.py
tests/test_pylast.py

Fix: _collect_nodes() break if there are no child nodes

---

pylast/__init__.py
tests/test_pylast_album.py
tests/test_pylast_artist.py
tests/test_pylast_library.py
tests/test_pylast_librefm.py
tests/test_pylast_network.py
tests/test_pylast_track.py
tests/test_pylast_user.py

In the process of adding more tests I found more dead Last.fm stuff.
Continuation of #211, #218, #222, #223, #224, #225.
The last 1.9.0 release was at 72.03% coverage, the next 2.0.0 will be at around 95.34%.

Add more tests and remove more dead Last.fm stuff

---

COPYING
pylast/__init__.py
tests/test_pylast_artist.py
tests/test_pylast_network.py

```
This page contains the following errors:
error on line 2 at column 73: Namespace prefix opensearch on Query is not defined
error on line 3 at column 25: Namespace prefix opensearch on totalResults is not defined
error on line 4 at column 23: Namespace prefix opensearch on startIndex is not defined
error on line 5 at column 25: Namespace prefix opensearch on itemsPerPage is not defined
Below is a rendering of the page up to the first error.
```
https://www.last.fm/api/show/track.search
https://ws.audioscrobbler.com/2.0/?method=track.search&track=Believe&api_key=ENTER_YOUR_API_KEY
This was worked around in https://github.com/pylast/pylast/issues/152 by removing the malformed "opensearch:" prefix. 
(Temporarily removing that gives `pylast.MalformedResponseError: Malformed response from …

Fix search.get_total_result_count()

---

pylast/__init__.py

Dear pylast maintainers,
The quality of user avatars was previously fixed to `small` despite the fact that versions up to `extralarge` are available. I reused the constants utilized for artist and album images (`COVER_EXTRA_LARGE, COVER_LARGE, COVER_MEDIUM, COVER_SMALL`) to add a size parameter to `User.get_image`.
With kind regards,
Philip Trauner

Added parameter to retrieve higher resolution user avatars

---

pylast/__init__.py
tests/test_pylast_user.py

Unix timestamps are currently returned as strings. I'd argue that while this behaviour is true to the `xml` schema it doesn't make much sense. 
```xml
<registered unixtime="1037793040">2002-11-20 11:50</registered>
```
They even kind of acknowledged this in the `json` schema. (Probably because someone at last realized that it doesn't make any sense to do date conversion in the API)
```json
registered: {
"#text": 1037793040,
"unixtime": "1037793040"
}
```
I don't know if a simple "cast" to int is the right choice here, even if the string returned by the API should always be a number. Should I add any additional validation to prevent a possible crash?

Return unix timestamp as int

---

setup.py

Fixes https://github.com/pylast/pylast/issues/239. 
Update python_requires to specify the exact x.y.z 2.7.10 version required.
(From HTTPS changes in #178.)

Update python_requires to 2.7.10+

---

pylast/__init__.py
tests/test_pylast_artist.py

Fixes #242.
`Artist.get_top_albums` with `limit=100` returns 100 per page for some artists, but only returns 50 per page for others.
Use paging to load as many pages as needed to return the required limit.

Use paging to get all 'limit' items for Artist.get_top_albums

---

pylast/__init__.py

Cherry-picked from #200:
> Checking if a request is cached or not took ~6sec / item vs <0.01sec now, because `__contains__` wasn't definied for the `_ShelfCacheBackend` class and it iterated over each cache key on every check

Fix serious cache key lookup performance problem

---

pylast/__init__.py

For readability. 
New in Python 2.7+. 
https://docs.python.org/2/library/sys.html#sys.version_info
And treat only Python 2 as the special case, not Python 3.
For Python 4 compatibility.
https://astrofrog.github.io/blog/2016/01/12/stop-writing-python-4-incompatible-code/

Simplify version checking

---

pylast/__init__.py
tests/test_pylast_track.py

Fixes #249 
* Add the limit parameter to the track.getSimilar query

Add missing limit parameter for track.getSimilar

---

tests/test_user.py

One we know has more than two top tracks, rather than a new test user who might not.
Fixes #253.

Test against a certain user

---

pylast/__init__.py
tests/test_user.py

Fixes #257.
* When building the charts from the response from Last.fm, it was using some common code for charts for artists, albums and tracks.
* It was creating artist, album or track objects by passing it the `artist` and `name` (and network).
* But that only makes sense for album and track. For artists, there is no `artist` field, the `name` is the artist's name.

Fix user.get_weekly_artist_charts

---

setup.py

Fixes #256.
* Use README.md as the `long_description` on PyPI
* https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
* https://github.com/di/markdown-description-example

Use Markdown on PyPI

---

.gitignore
pylast/__init__.py
pytest.ini

```console
$ pytest -Wd -k test_init_with_token
================================================================= test session starts ==================================================================
platform darwin -- Python 3.6.4, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
Using --randomly-seed=1523434571
rootdir: /Users/hugo/github/pylast, inifile:
plugins: xdist-1.20.1, rerunfailures-3.1, randomly-1.2.3, forked-0.2, expect-1.1.0, cov-2.5.1, flaky-3.4.0
collected 130 items / 129 deselected
tests/test_network.py .                                                                                                                          [100%]
===Flaky Test Report===
test_init_with_token passed 1 out of the required 1 times. Success!
===End Flaky Test Report=== …
```

Close HTTPSConnection in case of exception

---

README.md
pylast/__init__.py
tests/test_album.py
tests/test_artist.py
tests/test_country.py
tests/test_library.py
tests/test_librefm.py
tests/test_network.py
tests/test_pylast.py
tests/test_tag.py
tests/test_track.py
tests/test_user.py

For #261.
* Like #262:
* Save images on `Artist.get_info` and `ArtistSearch.get_next_page`
* Save images on `Track.get_info` and `TrackSearch.get_next_page`
* Refactor this and #262 to store them in `info["image"]` rather than `images` for extensibility
* In the future, allows us to put the other info from `.getInfo`/`.get_next_page` in the same `info` variable
* Some test refactoring

 Save artist images and refactor album images

---

pylast/__init__.py

Fixes #266.
* In one case, a list of loved tracks includes one `<track>` that looks like an artist
* It has a single `<name>` for the `<artist>`, but none for the `<track>`
* If this happens, skip it

'Tracks' with only one <name> are artists not tracks, skip them

---

MANIFEST.in
RELEASING.md
pylast/__init__.py
pylast/version.py
setup.py
tox.ini

* Only include the version in one place
* Makes releasing that little bit easier
https://packaging.python.org/guides/single-sourcing-package-version/

Single-source the package version

---

tox.ini

PyYAML 4.1 has been released, supporting Python 3.7.
We can now revert workaround https://github.com/pylast/pylast/pull/255/commits/f2ec5bc57ef06c0f8db9a92f2ebb628460e358aa from PR https://github.com/pylast/pylast/pull/255.

Revert PyYAML workaround for Python 3.7

---

.travis.yml
tox.ini

Fixes #278.
* Add official Python 3.7 to CI
* It requires Xenial and sudo: https://github.com/travis-ci/travis-ci/issues/9069
* Keep `3.7-dev` and `3.6-dev` for now, even though they've not been updated for a while
* `3.6-dev` is 3.6.5+, but 3.6.6 is the latest
* `3.7-dev` is 3.7.0a4+, but 3.7.0 is the latest
* Can remove them in the future if they don't update

Test on official Python 3.7

---

.travis.yml
tox.ini

Fixes #286. 
* Add 3.8-dev
* Remove 3.7-dev
* Remove 3.6-dev
There's been no change since https://github.com/pylast/pylast/pull/279, July 2018:
* `3.6-dev` is 3.6.5+, but 3.6.7 is the latest
* `3.7-dev` is 3.7.0a4+, but 3.7.1 is the latest

CI: Test on 3.8-dev, remove 3.6-dev and 3.7-dev

---

.travis.yml
CHANGELOG.md
README.md
clonedigger.sh
pylast/__init__.py
pylast/version.py
setup.py
tests/test_user.py
tests/unicode_test.py
tox.ini

For #265.
* [Fail early at import time](https://python3statement.org/practicalities/#fail-early-at-import-time)
* [Fail early in setup.py](https://python3statement.org/practicalities/#fail-early-in-setuppy)
* Remove Python 2 code
* Update `python_requires`, Trove classifiers and README
* Change deprecation warning to error
* Bump major version
* Upgrade Python syntax with ``pyupgrade `find . -name "*.py"` --py3-plus``

Drop support for legacy Python 2

---

.travis.yml
README.md
pylast/__init__.py
setup.py
tox.ini

* It's not long until Python 3.4's EOL on 2019-03-16
* Python 3.4 isn't used much
* A backwards-incompatible release is coming up soon (dropping Python 2 https://github.com/pylast/pylast/pull/281) so  it's a good time to bundle this into a major version release
* Upgrade Python syntax with ``pyupgrade `find . -name "*.py"` --py3-plus``
* Includes PR https://github.com/pylast/pylast/pull/281 to avoid merge conflicts
Here's the pip installs for pylast from PyPI for last month:
| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  41.59% |     2,123 |
|      3.6 |  36.85% |     1,881 |
|      3.5 |   8.85% |       452 |
| null     |   5.99% |       306 |
|      3.7 |   5.80% |       296 |
|      3.4 |   0.82% |        42 | …

Drop support for legacy Python 3.4

---

tests/test_network.py
tests/test_pylast.py
tests/test_track.py
tox.ini

Some tests (`test_scrobble`, `test_unlove`) were sometimes failing, as the write API action they'd just made wasn't showing in the read API assert. 
This could be due:
* to parallel build jobs running the same test at the same time mitigated by running tests in a random order, and only running on a single Python version
* there may a small delay in Last.fm updating the write before returning the read, mitigated by a `time.sleep(1)`

Fix the build

---

CHANGELOG.md
pylast/__init__.py
tests/test_album.py
tests/test_network.py
tests/test_user.py

Fixes #298.
* Deprecate `User.get_artist_tracks` as Last.fm will remove it soon:
* > We will be removing user.getArtistTracks from the public API soon. The new scrobble storage back-end doesn't support it, and the results returned by the method are slowly going out of date, as it's still powered by the legacy back-end.
* > The timeline for deprecation is sometime before May 2019.
* Add support for new `user.getTrackScrobbles`, which can partially replace `User.get_artist_tracks`
* > However there is a new method user.getTrackScrobbles which is just like user.getArtistTracks, except also takes a "track" parameter. This covers the most frequent use cases for the getArtistTracks which have seen (such as "find my first scrobble of a specific song" or …

Deprecate User.get_artist_tracks, add user.getTrackScrobbles

---

README.md
setup.cfg
tests/test_album.py

Starting with wheel 0.32.0 (2018-09-29), the "license_file" option is deprecated.
https://wheel.readthedocs.io/en/stable/news.html
The wheel will continue to include COPYING, it is now included automatically:
https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
---
Also update a badge link.

Remove deprecated license_file from setup.cfg

---

src/pylast/__init__.py
tests/test_album.py
tests/test_user.py

Continuation of https://github.com/pylast/pylast/issues/298.
* Last.fm's `user.getArtistTracks` has now been deprecated by Last.fm and is no longer available
* Last.fm returns a "Deprecated - This type of request is no longer supported" error when calling it
* Change one test which called it to check for this error
* Remove another test which called it
* A future version of pylast will remove its `User.get_artist_tracks` altogether

Update user.get_artist_tracks tests

---

src/pylast/__init__.py
tests/test_user.py

The `GetTopAlbums` API call returns album art information with each album in the top album list.
We should store this in the `Album() `info variable, so we don't have to follow up with an additional `GetInfo()` call if we want the Album Art.
This change means that calling both `user.get_top_albums()`, and then `album.get_cover_image()`, only requires a single API Call.
*` _extract_top_albums()` now extracts Image URLs from the returned `GetTopAlbumResponse`
* This is saved to a dict, which is passed to an `Album()` constructor as info.
* This adds an additional assert in `test_user.py`

Store Album Art URLs when you call GetTopAlbums.

---

src/pylast/__init__.py

Fixes #309 
* If there's a now playing track, we remove that from the `get_recent_tracks`
* To respect the `limit` parameter, request one extra, just in case one is now playing
* And slice the result before return, to ensure that `limit` is returned, not `limit + 1`

Respect get_recent_tracks' limit when there's a now playing track

---

.pre-commit-config.yaml
.travis.yml
src/pylast/__init__.py
tests/test_librefm.py
tests/test_pylast.py
tests/unicode_test.py
tox.ini

Fixes #308.
Looks like Last.fm removed `tag.get_weekly_artist_charts` / `Tag.getWeeklyArtistChart` as part of their "re-imagining". It's no longer listed on the API page:
* https://www.last.fm/api/
It was removed from the docs between 13 and 14th January 2016:
* https://web.archive.org/web/20160113041418/http://www.last.fm/api
* https://web.archive.org/web/20160114204951/http://www.last.fm/api
There's also no test for `tag.get_weekly_artist_charts`.
This updates the docstring, and also adds pre-commit for lint.

Update get_weekly_artist_charts docstring

---

.pre-commit-config.yaml
setup.py
src/pylast/__init__.py
tests/unicode_test.py

* Python 2.7 was dropped in pylast 3.0, released on 2019-01-01
* https://github.com/pylast/pylast/releases/tag/3.0.0
* It's been long enough, let's remove the warnings/errors when attempting to use on Python 2
* `python_requires` should stop this happening with recent pip

Remove Python 2 warnings, apply lint updates

---

.pre-commit-config.yaml
.travis.yml
INSTALL
MANIFEST.in
README.md
setup.cfg
setup.py
src/pylast/__init__.py
tests/test_artist.py
tests/test_user.py
tests/unicode_test.py
tox.ini

* Test on Python 3.8 final
* Xfail the two failing tests so as not to impede the others
* Mock is part of stdlib in Python 3, no need to install package
* Post-Black tidy up
* Other tox, .travis.yml, pre-commit things

Test updates

---

MANIFEST.in
RELEASING.md
setup.py
src/pylast/__init__.py
src/pylast/version.py

No editing of files, just add the version tag.
Can check with:
```console
$ python setup.py --version
3.1.1.dev45
```

Use setuptools_scm to simplify versioning during release

---

.github/workflows/lint.yml
.pre-commit-config.yaml
setup.cfg

The wheel filename contained `py2.py3`, indicating Python 2 support.
> _Universal Wheels_ are wheels that are pure Python (i.e. contain no compiled extensions) and support Python 2 and 3. This is a wheel that can be installed anywhere by pip.
...
> Only use the `--universal` setting, if:
> * Your project runs on Python 2 and 3 with no changes (i.e. it does not require 2to3).
> * Your project does not have any C extensions.
>
> Beware that `bdist_wheel` does not currently have any checks to warn if you use the setting inappropriately.
https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels
> _Pure Python Wheels_ that are not “universal” are wheels that are pure Python (i.e. contain no compiled extensions), but don’t natively support both Python 2 and 3. …

Only Python 3 is supported: don't create universal wheel

---

.github/ISSUE_TEMPLATE.md
.github/labels.yml
.github/release-drafter.yml
.github/workflows/labels.yml
.github/workflows/release-drafter.yml
.pre-commit-config.yaml
tests/test_pylast.py

* Use https://github.com/micnncim/action-label-syncer to import labels for use with https://keepachangelog.com/en/1.0.0/
* Existing labels were first exported using https://github.com/micnncim/label-exporter
* Use https://github.com/release-drafter/release-drafter to draft a release as PRs are merged, using Keep a Changelog labels
RELEASING.md will need updating, will do so after the next release.

Use Release Drafter to draft releases

---

.pre-commit-config.yaml
src/pylast/__init__.py
tests/test_user.py
tox.ini

Fixes #313.
* Fix a regression introduced in https://github.com/pylast/pylast/pull/310
* Allow `get_recent_tracks` to be called with `limit=None`

Fix regression calling get_recent_tracks with limit=None

---

.github/workflows/lint.yml
setup.py

For some reason, when the last PR was merged, the lint failed because of an apparently outdated cache:
```
Run tox -e lint
lint create: /home/runner/work/pylast/pylast/.tox/lint
lint installdeps: pre-commit
lint installed: appdirs==1.4.3,cfgv==3.1.0,distlib==0.3.0,filelock==3.0.12,identify==1.4.11,nodeenv==1.3.5,pre-commit==2.1.1,PyYAML==5.3,six==1.14.0,toml==0.10.0,virtualenv==20.0.8
lint run-test-pre: PYTHONHASHSEED='3856264503'
lint run-test: commands[0] | pre-commit run --all-files
pyupgrade................................................................Failed
- hook id: pyupgrade
- exit code: 1
Executable `/home/runner/.cache/pre-commit/repoy32i7vy1/py_env-python3.8/bin/python` not found
black....................................................................Failed
- hook id: black …
```

GHA: Fix lint cache

---

tests/test_user.py

> _New in version 3.5_: The name `assertNotRegexpMatches` is a deprecated alias for `assertNotRegex()`.
https://docs.python.org/3.5/library/unittest.html#unittest.TestCase.assertRegexpMatches

Fix DeprecationWarning: Please use assertRegex instead

---

src/pylast/__init__.py

Fixes #
* Raise a WSError if the API response contains a non-200 code, instead of failing to interpret the body and raising a MalformedResponseError

Improve handling of error responses from the API

---

.pre-commit-config.yaml
RELEASING.md
src/pylast/__init__.py
tests/test_artist.py

Fixes #325.
* `artist.get_bio_content()` causes an exception for an artist with no biography, because it tries to get data from an empty `<content/>`
* Instead, if it is `None`, return `None`
* Will also fix for other `artist.get_bio_X()` functions, and other things that call `_extract_cdata_from_request` 
This happens because there's no biography for this artist.
The XML from the API has an empty `<content/>`:
```xml
<lfm status="ok">
<artist>
<name>Mr Sizef Unquote</name>
<url>https://www.last.fm/music/Mr+Sizef+++Unquote</url>
<image size="small"/>
<image size="medium"/>
<image size="large"/>
<image size="extralarge"/>
<image size="mega"/>
<image size=""/>
<streamable>0</streamable>
<ontour>0</ontour>
<stats>
<listeners>6</listeners> …
```

Fix artist.get_bio_content() to return None if bio is empty

---

.github/workflows/lint.yml
.pre-commit-config.yaml
src/pylast/__init__.py
tests/test_album.py
tests/test_artist.py
tests/test_country.py
tests/test_library.py
tests/test_librefm.py
tests/test_network.py
tests/test_pylast.py
tests/test_tag.py
tests/test_track.py
tests/test_user.py

Fixes #329.
* `User.get_now_playing`: Add `album` name and cover artwork `image` URLs to `info`
* Done like to https://github.com/pylast/pylast/pull/307 for `user.get_top_albums`
* Also convert from unittest to pytest

User.get_now_playing: Add album and cover image to info

---

.pre-commit-config.yaml
src/pylast/__init__.py
tests/test_artist.py
tox.ini

Fixes #317.
* [Last.fm announced](https://support.last.fm/t/api-announcement/202) that artist images were never meant to be available, in line with their API Terms of Use
* They replaced the images with default star images
* We therefore don't need to maintain `Artist.get_cover_image` in the future, so let's deprecate it first

Deprecate Artist.get_cover_image, they're no longer available from Last.fm

---

tests/test_artist.py
tests/test_network.py
tests/test_pylast.py
tests/test_track.py

* Because test are run using a real (test) account on Last.fm, sometimes one of the parallel jobs changes the state on the network and causes another job to fail (eg. last `master` https://travis-ci.org/github/pylast/pylast/builds/701542153)
* Let's only do write tests with a single Python version/CI job (currently 3.8), to isolate potential conflicts

Only test write operations on a single Python version to avoid collision failures

---

.github/workflows/lint.yml
.pre-commit-config.yaml
.travis.yml
README.md
setup.cfg
setup.py
src/pylast/__init__.py
tests/test_artist.py
tests/test_librefm.py
tests/test_network.py
tests/test_pylast.py
tests/test_track.py
tests/test_user.py
tests/unicode_test.py

* Drop support for EOL Python 3.5
* Update Black, isort and some other config

Drop support for EOL Python 3.5

---

src/pylast/__init__.py
tests/test_artist.py
tests/test_user.py

Fixes #344.
* Remove deprecated `Artist.get_cover_image`
* Remove deprecated `User.get_artist_tracks`
* Remove deprecated `STATUS_TOKEN_ERROR`

Remove deprecated Artist.get_cover_image, User.get_artist_tracks and STATUS_TOKEN_ERROR

---

src/pylast/__init__.py

Fixes #353 
* Default username context of track to the current user if not set
* LastFM API seems to have problems interpreting the 'username' parameter when it's included in the post body. Since it's only used to retrieve the context of a track/album/artist (afaik) I would propose this as a temporary solution only until LastFM manages to fix this on their end.
Used the following piece of code to reproduce the problem:
```python
import pylast
API_KEY = "***"
API_SECRET = "***"
username = "***"
password_hash = "***"
network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET,
username=username, password_hash=password_hash)
track = network.get_authenticated_user().get_recent_tracks(limit=1)[0]
playcount = track.track.get_userplaycount() …
```

Bugfix for get_userloved and get_userplaycount resulting in an empty response from the server

---

.pre-commit-config.yaml
src/pylast/__init__.py
tests/test_album.py
tests/test_network.py

Code fixes:
* Fix `artist.get_bio_content()` for when bio is empty: previously Last.fm returned `<content/>` (https://github.com/pylast/pylast/pull/326), but now it doesn't even return a `<content/>` section 
Test fixes:
* xfail `test_track_mbid`: Last.fm is broken and returning "Track not found"
* https://support.last.fm/t/track-getinfo-with-mbid-returns-6-track-not-found/47905
* Fix `test_get_cover_image`: the test image is now gif not png
* Fix `test_artist_mbid`: check more than one title
Test updates:
* Update pre-commit and add quarterly `autoupdate_schedule`

Fix artist.get_bio_content() when bio is empty + other test fixes

---

.github/workflows/test.yml
tests/test_network.py

Committed via https://github.com/asottile/all-repos

Replace deprecated pypy3 with pypy-3.8

---

.editorconfig
.github/release-drafter.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/release-drafter.yml
.github/workflows/test.yml
.pre-commit-config.yaml
setup.cfg
setup.py

* Convert setup.py to static setup.cfg with https://github.com/asottile/setup-py-upgrade and format with https://github.com/asottile/setup-cfg-fmt 
* CI: Use actions/setup-python's pip cache
* Fix a typo so release drafter runs for this org

Convert setup.py to static setup.cfg and format with setup-cfg-fmt

---

setup.cfg
src/pylast/__init__.py

* Importing `pkg_resources` is slow, so instead use `importlib.metadata` (stdlib for 3.8+, and backport for <=3.7
* For example: 0.519s -> 0.153s
Charts created using:
```sh
python -X importtime -c 'import pylast; print(pylast.__version__)' 2> import.log
tuna import.log
```

Speedup: Use faster `importlib.metadata` for getting version

---

src/pylast/__init__.py

To get an unlimited number of top tracks, `_get_things` expects
`params['limit']` to be set to `None`. However, this can't happen here
because `None` is falsy.
Fixes #366.

Set `get_top_tracks` limit even if it's `None`, to get unlimited user `top_tracks`

---

.github/workflows/test.yml
.pre-commit-config.yaml
README.md
setup.cfg
tox.ini

Python 3.6 is EOL next month:
| cycle | latest |  release   |    eol     |
|:------|:-------|:----------:|:----------:|
| 3.10  | 3.10.0 | 2021-10-04 | 2026-10-04 |
| 3.9   | 3.9.9  | 2020-10-05 | 2025-10-05 |
| 3.8   | 3.8.12 | 2019-10-14 | 2024-10-14 |
| 3.7   | 3.7.12 | 2018-06-27 | 2023-06-27 |
| 3.6   | 3.6.15 | 2016-12-23 | 2021-12-23 |
And little used. Here's the pip installs for pylast from PyPI for October 2021:
| category | percent | downloads |
|:---------|--------:|----------:|
| 3.9      |  65.55% |    37,605 |
| 3.8      |  23.05% |    13,223 |
| null     |   7.98% |     4,577 |
| 3.7      |   1.78% |     1,021 |
| 3.10     |   0.72% |       414 |
| 3.6      |   0.60% |       342 |
| 2.7      |   0.32% |       183 |
| 3.11     |   0.01% |         3 |
| 3.5      |   0.01% | …

Drop support for Python 3.6

---

src/pylast/__init__.py
tests/unicode_test.py

Fixes https://github.com/pylast/pylast/issues/381
* In rare cases (I've seen it only once) a Last.fm response can contain invalid XML characters, such as a control character
* For performance, let's only strip them out when the XML parser raises an exception, and then try parsing again
* See also https://stackoverflow.com/a/62099920/724176

Strip invalid XML characters from response

---

.github/workflows/test.yml
.pre-commit-config.yaml
setup.cfg
tox.ini

* Temporarily undo https://github.com/pylast/pylast/pull/378 to make a release with some deprecations
* The deprecations can then be removed at the same time as dropping 3.6

Restore support for Python 3.6

---

pytest.ini
src/pylast/__init__.py
tests/test_artist.py
tests/test_network.py
tests/test_track.py

Fixes #
* Last.fm has deprecated the Radio API and the `streamable` attribute is also deprecated and will be removed at some point
* https://www.last.fm/api/radio
* https://support.last.fm/t/is-the-streamable-attribute-broken-it-always-returns-0/39723/3
* Let's `return False` from both `is_streamable()` and the `is_fulltrack_available()`, and deprecate them
* They will be removed in the upcoming pylast 5.0.0
Also:
* A couple of `xfail`s now pass, remove them and set `xfail_strict=true` so we're notified when others start passing

Deprecate is_streamable and is_fulltrack_available

---

src/pylast/__init__.py
tests/test_artist.py
tests/test_track.py

* Remove methods deprecated in [#384](https://github.com/pylast/pylast/pull/384)
* Last.fm has [deprecated the Radio API](https://www.last.fm/api/radio) and [the `streamable` attribute is also deprecated and will be removed at some point](https://support.last.fm/t/is-the-streamable-attribute-broken-it-always-returns-0/39723/3)

Remove deprecated `is_streamable` and `is_fulltrack_available`

---

.pre-commit-config.yaml
setup.cfg
src/pylast/__init__.py
tests/test_network.py

Fixes #361.
* Minimal changes to switch to HTTPX
* Further improvements welcome in the future
* Switching to HTTPX means there's scope for breaking changes (for example, some underlying networking exceptions have changed) so now is a good time to switch because Python 3.6 is being dropped (https://github.com/pylast/pylast/pull/378) and will warrant a major bump

Replace http.client with HTTPX

---

tox.ini

Coverage has been missing from Codecov for a while.
Before:
```
[2022-02-27T14:35:10.483Z] ['info'] Searching for coverage files...
[2022-02-27T14:35:10.513Z] ['info'] Warning: Some files located via search were excluded from upload.
[2022-02-27T14:35:10.513Z] ['info'] If Codecov did not locate your files, please review [docs.codecov.com/docs/supported-report-formats](https://docs.codecov.com/docs/supported-report-formats)
[2022-02-27T14:35:10.513Z] ['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`
```
After:
```
[2022-02-27T14:39:45.682Z] ['info'] => Found 1 possible coverage files:
coverage.xml
[2022-02-27T14:39:45.682Z] ['info'] Processing /home/runner/work/pylast/pylast/coverage.xml...
```

Output coverage XML for Codecov to upload

---

src/pylast/__init__.py
tests/test_album.py

Fixes #389
* If an album has no MBID (the `album.getinfo` XML has `<mbid/>` instead of something like `<mbid>0b6b4ba0-d36f-47bd-b4ea-6a5b91842d29</mbid>`), then return `None` instead of raising an `AttributeError`

If album has no MBID, album.get_getmbid() returns None

---

README.md
src/pylast/__init__.py

* Log method names at `INFO` level instead of `DEBUG`: "Confirmation that things are working as expected"
* Also log API return data at `DEBUG` level: "Detailed information, typically of interest only when diagnosing problems"
* https://docs.python.org/3/howto/logging.html#when-to-use-logging

Log method names at INFO level, also log API return data at DEBUG level

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/require-pr-label.yml
.github/workflows/test.yml
.pre-commit-config.yaml
setup.cfg
setup.py
tests/test_track.py
tox.ini

Fixes #
Python 3.11 beta is out on Friday with full release in October:
* 3.11.0 beta 1: Friday, 2022-05-06
* 3.11.0 final: Monday, 2022-10-03
https://peps.python.org/pep-0664/
* Test `3.11-dev` on GitHub Actions
* Add `py311` to `tox.ini`
* Add Trove classifier
* Update some config

Support Python 3.11

---

tests/test_track.py

* Workaround Last.fm bug where some tracks are returning `"duration": "0"`
* Discussed further at https://support.last.fm/t/missing-track-lengths-on-various-songs/57615/22?u=hvk
* Looks like they manually fixed this Daft Punk track after it was reported in that thread, let's switch over

Fix test_track_get_duration

---

.github/workflows/test.yml

* Python 3.11.0 final was [released yesterday](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 
* Let's switch `3.11-dev` to `3.11` for GitHub Actions

Test on Python 3.11 final

---

README.md

Describe authentication with OAuth token
Fixes #417

Document how to authenticate with a session key

---

.github/workflows/test.yml
.pre-commit-config.yaml
README.md
pyproject.toml
src/pylast/__init__.py
tests/test_album.py
tests/test_library.py
tests/test_librefm.py
tests/test_network.py
tests/test_pylast.py
tests/test_user.py
tox.ini

* Drop support for Python 3.7, EOL this month
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0537/
* Not planning a major bump, because `requires-python = ">=3.8"` will make sure people get the right version
* Fix a test that checking for .gif, the data is now .png
* Some test refactoring, including replace helper methods that were useful with unittest and less so with pytest

Drop support for EOL Python 3.7

---

src/pylast/__init__.py

- fix docstrings with inaccurate descriptions
While going through the pyLast documentation, I noticed that a few functions had inaccurate descriptions. The proper use of these functions should be intuitive from their names, but I thought it still might be useful to fix their docstrings. Let me know if there are any issues with these changes. Thanks!

Fix incorrect docstrings

---

src/pylast/__init__.py

This PR is aimed to prevent the possible misuse of UTC timestamp parameters by providing a type hint.
Even though the docstrings say that timestamps should be the "integer number of seconds", it is still quite tempting to expect that a method call like this one will produce a sensible result:
```python
ts = datetime(2021, 10, 19, 10, 1).timestamp() # Returns number of seconds, but as a float with zero fractional part.
lastfm_user.get_recent_tracks(time_from=ts)
```
However, pylast will translate this value into `?from=1634680860.0` (note the trailing 0), which LastFM API simply ignores and treats as missing. As a results, no filtering by scrobble date is applied.
* UNIX timestamp parameters are required to have the type of `int` or `Optional[int]`. …

Add type annotations to methods that take timestamp parameter

---

src/pylast/__init__.py

We've been getting lots of errors on the CI, for example https://github.com/pylast/pylast/actions/runs/7532231359:
```
======== 81 passed, 9 skipped, 1 xfailed, 50 errors in 84.73s (0:01:24) ========
```
```pytb
pylast.NetworkError: NetworkError: The read operation timed out
```
Coming from:
```pytb
httpx.ReadTimeout: The read operation timed out
```
Coming from:
```pytb
httpcore.ReadTimeout: The read operation timed out
```
Coming from:
```pytb
= <ssl.SSLSocket [closed] fd=-1, family=30, type=1, proto=0>, len = 65536, buffer = None
def read(self, len=1024, buffer=None):
"""Read up to LEN bytes and return them.
Return zero-length string on EOF."""
self._checkClosed()
if self._sslobj is None:
raise ValueError("Read on closed or unwrapped SSL socket.")
try:
if buffer is not None:
return …
```

Double read timeout to fix 'The read operation timed out'

---

README.md

Fixes #454
* This pull request updates the link to example_test_pylast.yaml in the in the Testing Section of README.md
* In Issue #454, the link from README.md in the GitHub repo would properly direct to [example_test_pylast.yaml](https://github.com/pylast/pylast/blob/main/example_test_pylast.yaml), but the link on the website would direct users to a [404: Page Not Found](https://pypi.org/project/pylast/example_test_pylast.yaml/) error due to the Markdown code found here:
*  On line 145: `[example_test_pylast.yaml](example_test_pylast.yaml)`
* This solution updates that code to: 
* `[example_test_pylast.yaml](https://github.com/pylast/pylast/blob/main/example_test_pylast.yaml)`
**Before:** 
**Proposed Solution:**
Thank you so much for taking a look, and please let me know if there are any …

Update example_test_pylast.yaml Link in README.md 

---

.gitignore
.pre-commit-config.yaml
pyproject.toml
src/pylast/__init__.py

Like https://github.com/hugovk/tinytext/pull/195.
With Python 3.13.0rc2:
```sh
python -X importtime -c "import pylast" 2> import.log && tuna import.log
```
---
httpx remains the slowest import, but it's very likely it is needed when running pylast. We could replace it with something faster to import like urllib3, but that's for another time.
```console
❯ hyperfine --warmup 32  'python3 -c "import httpx"' 'python3 -c "import urllib3"'
Benchmark 1: python3 -c "import httpx"
Time (mean ± σ):     146.8 ms ± 114.8 ms    [User: 104.7 ms, System: 18.3 ms]
Range (min … max):   119.2 ms … 685.5 ms    24 runs
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or …
```

Generate `__version__` at build to avoid slow `importlib.metadata` import

---

.github/workflows/deploy.yml
.github/workflows/test.yml

* https://github.blog/news-insights/product-news/introducing-artifact-attestations-now-in-public-beta/
* https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
Also use uv for the tests workflow.

Attest build provenance using GitHub's actions/attest-build-provenance

---

.github/workflows/deploy.yml
.github/workflows/labels.yml
.github/workflows/lint.yml
.github/workflows/test.yml

No cache: 1m 19s
https://github.com/pylast/pylast/actions/runs/11597729187/job/32291921076
With cache: 14s
https://github.com/pylast/pylast/actions/runs/11597757451/job/32292016450
No cache: 49s
https://github.com/pylast/pylast/actions/runs/11597731048/job/32291927858
With cache: 14s
https://github.com/pylast/pylast/actions/runs/11597758972/job/32292022348
---
Also fix warnigs from [zizmor](https://github.com/woodruffw/zizmor).

Replace pre-commit/action with faster tox-dev/action-pre-commit-uv

---

.github/workflows/deploy.yml

Generating PyPI's digital attestations should be enough (https://docs.pypi.org/attestations/), we don't _also_ need to use https://github.com/actions/attest-build-provenance.
And we've not made any releases yet with GH attestations (added in https://github.com/pylast/pylast/pull/462).

Only create PyPI digital attestations (PEP 740)

---

pyproject.toml
src/pylast/__init__.py

Fixes https://github.com/pylast/pylast/issues/480
* Replace `collections.namedtuple` with `typing.NamedTuple` for `TopItem`, `SimilarItem`, `LibraryItem`, `PlayedTrack` and `LovedTrack`
* Remove unused `ImageSizes` and `Image`, their use was removed in https://github.com/pylast/pylast/commit/d3dba1475ab1615aae421d1e418f9134554c561c in 1.0.0. We're now on 5.x so I won't plan deprecations or a major bump.
* Add PYI to Ruff rules.

Replace `collections.namedtuple` with `typing.NamedTuple` and remove unused
