.editorconfig
pylast/__init__.py
tests/test_pylast.py

* Fix #124: don't compare to limit if limit is None (Network.get_top_tags)
* Remove unused argument
* Don't redefine built-ins
* Year is now 2015
* Rerun flaky tests up to 4 times 
* Add EditorConfig

Network.get_top_tags: don't compare to limit if limit is None

---

pylast/__init__.py
tests/test_pylast.py

Added functions User.get_tagged_tracks, User.get_tagged_albums and User.get_tagged_artist, plus test cases.

Support for User.GetPersonalTags

---

pylast/__init__.py
setup.py

Making pylast more robust after recent Last.fm API changes.
https://github.com/pylast/pylast/pull/145

Fix get_recent_tracks (and more)

---

.travis.yml
setup.py
tox.ini

And jiggle around the matrix, as the allowed_failures bit was ignored before.

Add Python 3.5 and 3.6

---

.travis.yml

Keeping Coveralls for now, may remove in the future.

Add Codecov for coverage

---

.gitignore
pylast/__init__.py
tests/test_pylast.py

Support authentication tokens to construct networks

---

pylast/__init__.py
tests/test_pylast.py

All links on www.last.fm are HTTPS now, and all languages are on one domain.

Update links to HTTPS; update lang links

---

pylast/__init__.py

Ahead of the 2.0.0 release.
This has been deprecated for six years, since https://github.com/pylast/pylast/blob/0.5.11/pylast.py

Remove deprecated code

---

pylast/__init__.py

Cherry-picked from https://github.com/pylast/pylast/pull/200.

Fix typos and style

---

pylast/__init__.py
tests/test_pylast.py

Cherry-picked from https://github.com/pylast/pylast/pull/200 plus a test.

Fix Album.get_tracks() positional argument

---

.travis.yml
tox.ini

In addition to existing Python 2.

Lint Python 3

---

pylast/__init__.py

Continuation of https://github.com/pylast/pylast/pull/211 and https://github.com/pylast/pylast/pull/218.

Remove code rendered redundant after removing deprecated code

---

pylast/__init__.py
tests/test_pylast.py
tests/test_pylast_artist.py
tests/test_pylast_network.py
tests/test_pylast_tag.py
tests/test_pylast_user.py

Also assume the XML is legal.
Continuation of #211, #218, #222, #223, #224, #225, #226.

No more skipping broken Last.fm and remove more dead Last.fm stuff

---

setup.py
tox.ini

And has been for nearly two years.
https://github.com/PyCQA/pycodestyle/issues/466
https://github.com/PyCQA/pycodestyle/issues/481

pep8 is now pycodestyle

---

README.md
pylast/__init__.py
setup.py
tests/test_pylast_network.py
tests/test_pylast_user.py

* Remove unnecessary parentheses
* Rename variables shadowing built-ins

Fix some PyCharm code inspection things

---

README.md
tox.ini

See https://github.com/pytest-dev/pytest/issues/1629.

pytest is recommended entry point

---

.travis.yml
tox.ini

https://snarky.ca/how-to-use-your-project-travis-to-help-test-python-itself/
To merge after the next release.

Be a good citizen: test 3.6-dev

---

setup.py

https://stackoverflow.com/a/44660547/724176

Require Python 2.7 or 3.4+

---

RELEASING.md

Update release checklist to remove develop branch

---

pylast/__init__.py
tests/test_pylast_track.py

I needed this for my own project, I hope it's useful.
I'm sorry that the date changed too, if needed I'll make another PR with the date left at 2017.

This adds the limit parameter to track.get_similar()

---

pylast/__init__.py
tests/test_pylast_album.py
tests/test_pylast_artist.py
tests/test_pylast_country.py
tests/test_pylast_tag.py
tests/test_pylast_user.py

Use more helpful assert methods

---

pylast/__init__.py

http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments
https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/

Do not use a mutable data structure for argument default

---

.travis.yml
setup.py
tox.ini

Python 3.7.0 beta 2 is out, 3.7.0 final due for release 2018-06-15.
https://www.python.org/dev/peps/pep-0537/#release-schedule

Add Python 3.7

---

README.md
pylast/__init__.py
tests/test_track.py

* https://docs.python.org/2.7/library/logging.html#logging.debug
* https://docs.pytest.org/en/latest/logging.html#live-logs

Replace print with logging

---

pylast/__init__.py
tests/test_pylast.py
tox.ini

https://github.com/PyCQA/pep8-naming

Add pep8-naming to flake8 and fix issues

---

pylast/__init__.py

Just some small things from https://github.com/asottile/pyupgrade.

Run pyupgrade

---

pylast/__init__.py

For #265.
* Upgrade Python syntax with pyupgrade
* UserWarning when importing on Python <3 https://python3statement.org/practicalities/\#runtime-warning-on-master

Deprecate Python 2

---

pylast/__init__.py
setup.cfg

Extract username from session

---

.github/workflows/lint.yml
.pre-commit-config.yaml

Example: https://github.com/pylast/pylast/runs/360190846

Lint with GitHub Actions

---

.github/labels.yml

Also `dependencies` label for dependabot.

Add automerge label for Mergify

---

README.md
setup.py

Add support for Python 3.9

---

.travis.yml

Add Python 3.9 final to Travis CI

---

src/pylast/__init__.py
tests/test_artist.py
tests/test_pylast.py

Fixes https://github.com/pylast/pylast/issues/354.
* https://github.com/pylast/pylast/pull/243 set the `limit` default to 1
* Instead default to 50
* Plus some refactoring

Set limit to 50 by default, not 1

---

.github/ISSUE_TEMPLATE.md
.github/labels.yml
.github/release-drafter.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.pre-commit-config.yaml
README.md
src/pylast/__init__.py
tests/test_pylast.py

Plus some other formatting and config changes, and do the write tests on Python 3.9, not 3.8.

Update copyright year

---

src/pylast/__init__.py

* Fixed unsafe creation of temp file for caching
* Improved the way how exceptions are raised. Exceptions explicitly raised in the code are now (subclasses of) `PyLastError`.

Fix unsafe creation of temp file for caching, and improve exception raising

---

README.md

There is no shout() method for the artist object.

Remove artist.shout("<3") in README.md

---

README.md
setup.py

Releasing today!
https://www.youtube.com/watch?v=AHT2l3hcIJg&ab_channel=PythonDiscord

Add support for Python 3.10

---

README.md
pyproject.toml
tox.ini

* Add support for Python 3.12
* Currently in alpha, beta out next month, full release in October
* Already tested via `3.12-dev`

Add support for Python 3.12

---

.github/workflows/deploy.yml
.github/workflows/test.yml
.pre-commit-config.yaml

* 🔒 https://github.com/pypi/pypi-oidc-private-beta-community
* https://docs.pypi.org/trusted-publishers/
Also update pre-commit, and test newest PyPy.

Publish to PyPI with a Trusted Publisher

---

.flake8
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/require-pr-label.yml

* Use https://github.com/hynek/build-and-inspect-python-package for deploying, it gives nice info about what is being uploaded
* Plus some other config updates

Use hynek/build-and-inspect-python-package

---

.flake8
.github/workflows/deploy.yml
.github/workflows/labels.yml
.github/workflows/lint.yml
.github/workflows/require-pr-label.yml
.pre-commit-config.yaml
pyproject.toml
src/pylast/__init__.py
tests/test_album.py
tests/test_artist.py
tests/test_country.py
tests/test_library.py
tests/test_librefm.py
tests/test_network.py
tests/test_pylast.py
tests/test_tag.py
tests/test_track.py
tests/test_user.py
tests/unicode_test.py
tox.ini

Replace Flake8 with Ruff

---

.github/workflows/test.yml
src/pylast/__init__.py

https://pypi.org/project/autotyping/
Lots more to do, but here's some easy ones.

Add type hints using autotyping

---

.github/workflows/test.yml
README.md
pyproject.toml
tox.ini

Add support for Python 3.14 and PyPy3.11

---

.github/renovate.json
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/release-drafter.yml
.github/workflows/require-pr-label.yml
.pre-commit-config.yaml
.yamlfmt.yaml
RELEASING.md
pyproject.toml
src/pylast/__init__.py
tests/test_album.py
tox.ini

Plus call `endswith` with a tuple, add more linting and update config.

Remove unnecessary `start=0` from `range()`
